## Introduction to oop in python:

...
one of the popular approch to solve a programming problem by creating an objects.This is kknown as object oriented programming.

An object has two characteristics:

    1.attributes(name,age,colour)
    2.behaviour(learn,study,singing,dance)
     
In python,the concept oop follow these things:
    
1.Inheritance
2.Encapsulation
3.Ploymorphism

class:
    
*A class is blueprint for the object or logical entity

object:

*Blue print of class or Insurance of the class or physical entity

Methods:

part of class and can be called with object 

constructions:

part of class and can be called automatically when the class object is

In [1]:
class className:
    # some functions and variables
    # function -- used to perform the specific activity
    # variables -- Data(memory)

SyntaxError: unexpected EOF while parsing (<ipython-input-1-a0dbd04cec25>, line 4)

In [ ]:
def test():
    print('Test() for function')
    return
test()

In [2]:
class Demo:
    def test(self):
        print("test()for the class and method")
        return

obj=Demo()   #object creation
obj.test()   #call for the method

test()for the class and method


In [3]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact

p1=Demo1()
print(p1.fact(5))


120


In [4]:
#def test(self,para1,para2)

In [5]:
class Demo2:
    
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("p1=",self.p1)
        print("p2=",self.p2)
        
c1=Demo2()
c1.Accept(10,20)
c1.display()

p1= 10
p2= 20


In [6]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1 + p2
    
c1= Demo2(10,20)
print(c1.add(100,200))

300


In [7]:

# some inheritance
# parent class
class Person(object):
    #constructor
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
    
# Derived class 
class Employee(Person):
    def isEmployee(self):
        return True
    
emp = Person("Anil")
print(emp.getName(),emp.isEmployee())
            
emp1 = Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())


Anil False
Akhil True


### python Numpy

Numpy arrays is a bit like python list.

Numpy array is a central data structure of the numpy lib

This lib actually short for 'Numeric python' or 'Numeric python'

In [8]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [9]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [10]:
lst = [1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [11]:
lst = [1,0,2.5,5,3,6,9,5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(8,)
float64


In [12]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [13]:
# RE-shapethe Given array
# numpy.reshape(arrayName,reshape,order='c')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# Append some Data -- Horizantally
# Append some Data-- Vertical

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [15]:
# Append some data -- vertical
# vstack(array1,array2) -- will be automatically arranged
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [16]:
# Generate random number from NP
a1 = np.random.normal(5,0,10)
print(a1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### numpy.zeroes() and numpy.one()

### Generate an array with  all zeros --numpy.zeros()

#numpy.

In [17]:
# numpy.zeros(shape,dtype = float,order = 'c')

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [19]:
a = np.matrix(np.ones((4,4),dtype=np.int64))
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2] = 5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [21]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3] = 14
np.asarray(A)[3][3] = 16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [22]:
# arrange() -- particular
# numpy.arrange(start,end,step)
# start - value
# end   - value
# step  - Gap between one value to another value

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [24]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [25]:
# Indexing and Slicing of numpy
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [26]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First Row :",a1[0])

First Row : [1 2 3]


In [27]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Second Row :",a1[1])

Second Row : [4 5 6]


In [28]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Second Row :",a1[1][1])

Second Row : 5


In [29]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [30]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing last column :",a1[:,2])

slicing last column : [3 6]


In [31]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[:,2])

Row and Column [3 6]


In [32]:
a1 = np.random.normal(5,1,10)
print(a1)

[5.80661765 4.96013483 6.07748465 4.30121579 4.02322522 4.16913266
 4.91241027 6.36720052 3.65127276 4.60176549]


In [33]:
# some math operation on given random numbers
# Min   -- returns the least number
# Max   -- returns the large number
# Mean  -- Mean
#Median -- Median
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value =",np.min(a1))
print("Max value =",np.max(a1))
print("Mean value =",np.mean(a1))
print("Median value =",np.median(a1))

[5.25534447 4.91845817 7.06002512 5.1358138  3.89555993 3.38133595
 5.35637895 6.13146365 4.2969736  5.59948094]
Min value = 3.381335946432321
Max value = 7.060025121446992
Mean value = 5.103083458289898
Median value = 5.195579137485147


In [34]:
# Multiply of 1D arrays
# numpy.dot(x,y) --

c1 = np.array([1,2])
c2 = np.array([4,5])
np.dot(c1,c2)

14

In [35]:
c1 = np.array([(1,2),(3,4)])
c2 = np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [36]:
b1 = np.array([(1,5),(6,9)])
b2 = np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

### Pandas Basics

Python is one of the popular programming language for data analysis

python is offering the lib called

Pandas Data Frames
   Data Analysis with python
   

In [37]:
import pandas as pd
dict = {"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
       "MobileNumber":[999,888,777,888,777,999],
       "Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b = pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [38]:
b.index = ["01","02","03","04","05","06"]
print(b)

      Name           EmailID  MobileNumber Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd


In [40]:
 # income of 6 states in america
import pandas as pd
income = pd.read_csv('income.csv')
print(income)

        GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0   04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1   04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  204000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3   04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4   04000US06  California  51755  55319  55734  57014  56134  54283  53367   
5   04000US08     Florida    123   4325   4565   9084  83123    423    987   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528  
5    345    765  
